version: '3.3'
services:
  redis:
    image: redis
    container_name: take-out-redis
    restart: always
    command: redis-server --requirepass 123456
    #    volumes:
    #      - /data/redis/data:/data
    ports:
      - '6379:6379'

  mysql:
    image: mysql
    container_name: take-out-mysql
    #    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
  #    volumes:
  #      - /data/mysql/data:/var/lib/mysql

  web:
    container_name: take-out-gin-server
    build:
      context: ./
      dockerfile: Dockerfile
    #    restart: always
    volumes:
      # 宿主机的配置文件挂载
      - ./config/application-dev.yaml:/app/config/application-dev.yaml
      # 日志目录
      - ./logger:/app/logger
    ports:
      - '8080:8080'