version: '3.3'
services:
  redis:
    image: redis
    container_name: take-out-redis
    restart: always
    command: redis-server --requirepass 123456
    #    volumes:
    #      - /data/redis/data:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "123456", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10

  mysql:
    image: mysql
    container_name: take-out-mysql
    #    restart: always
    volumes:
      - ./script/main.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
  #    volumes:
  #      - /data/mysql/data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysql", "-uroot", "-p123456", "-e", "SELECT 1" ]
      interval: 5s
      timeout: 10s
      retries: 10

  web:
    container_name: take-out-gin-server
    build:
      context: ./
      dockerfile: Dockerfile
#    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      # 宿主机的配置文件挂载
      - ./config/application-dev.yaml:/app/config/application-dev.yaml
      # 日志目录
      - ./logger:/app/logger
    ports:
      - '8080:8080'