# Linux
#version: '3.3'
#services:
#  redis:
#    image: redis
#    container_name: take-out-redis
#    restart: always
#    volumes:
#      - /data/redis/data:/data
#      - /data/redis/conf:/redis.conf:/usr/local/etc/redis/redis.conf
#      - /data/redis/logs:/logs
#    command:
#      - redis-server
#    ports:
#      - '6379:6379'
#  mysql:
#    image: mysql
#    container_name: take-out-mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      TZ: Asia/Shanghai
#      LANG: en_US.UTF-8
#    ports:
#      - '3306:3306'
#    volumes:
#      - /data/mysql/data:/var/lib/mysql
#      - /data/mysql/config:/config/my.cnf:/etc/mysql/my.cnf
#    command:
#      --max_connections=1000
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --default-authentication-plugin=mysql_native_password
#  web:
#    container_name: take-out-gin-server
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    restart: always
#    volumes:
#      # 这个共享卷是用来存放配置文件。
#      - /home/running/takeout/config/:/app/config/
#      # 该共享卷用来存储日志文件
#      - /home/running/takeout/logs/:/app/logger/
#    ports:
#      - '8080-8080'


# Windows
version: '3.3'
services:
  redis:
    image: redis
    container_name: take-out-redis
    restart: always
    command: redis-server --requirepass 123456
#    volumes:
#      - /data/redis/data:/data
    ports:
      - '6379:6379'

  mysql:
    image: mysql
    container_name: take-out-mysql
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
#    volumes:
#      - /data/mysql/data:/var/lib/mysql

  web:
    container_name: take-out-gin-server
    build:
      context: ./
      dockerfile: Dockerfile
#    restart: always
    volumes:
      # Windows 宿主机的配置文件挂载
      - E:\Code\Learn Go\my-take-out\config:/app/config
      # 日志目录
      - E:\Code\Learn Go\my-take-out\logs:/app/logger
    ports:
      - '8080:8080'