server:
  port: 8080
  # debug | release | test 运行环境
  level: debug

datasource:
  host: mysql
  port: 3306
  username: root
  password: 123456
  dbname: db1
  config: charset=utf8mb4&parseTime=True&loc=Local

jwt:
  admin:
    # 设置jwt签名加密时使用的秘钥
    secret: admin
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    name: token
  user:
    # 设置jwt签名加密时使用的秘钥
    secret: user
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    name: Authorization

log:
  level: debug
  filepath: ./logger/systemLog.txt

redis:
  host: redis
  port: 6379
  password: 123456
  data_base: 1